{
  try {
    new DateChannelHandler();
    Assert.fail();
  }
 catch (  ExceptionInInitializerError eiie) {
    Throwable throwable=eiie.getCause();
    Assert.assertSame(Exception.class,throwable.getClass());
    Assert.assertEquals("Forced Exception",throwable.getMessage());
  }
}
