{
  try {
    connect(userId,password);
  }
 catch (  XMPPException xmppe1) {
    String message1=xmppe1.getMessage();
    if (Validator.isNotNull(message1) && message1.contains("not-authorized")) {
      if (!PortletPropsValues.JABBER_IMPORT_USER_ENABLED) {
        if (_log.isDebugEnabled()) {
          _log.debug("User " + userId + " cannot connect to Jabber");
        }
        return;
      }
      if (_log.isDebugEnabled()) {
        _log.debug("Importing user " + userId + " because he cannot connect to Jabber");
      }
      try {
        importUser(userId,password);
        connect(userId,password);
      }
 catch (      XMPPException xmppe2) {
        String message2=xmppe2.getMessage();
        if (message2.contains("conflict(409)")) {
          _log.error("User " + userId + " already exists but password "+ "is not synchronized with Jabber");
        }
      }
catch (      Exception e) {
        _log.error(e,e);
      }
    }
  }
catch (  Exception e) {
    _log.error(e,e);
  }
}
