{
  try {
    return doInvoke(methodInvocation);
  }
 catch (  Exception e) {
    throw new WorkflowException(e);
  }
}
