{
  final RuntimeException runtimeException=new RuntimeException();
  RPCCallable<String> rpcCallable=new SyncProcessRPCCallable(new ProcessCallable<String>(){
    @Override public String call(){
      throw runtimeException;
    }
  }
);
  NoticeableFuture<String> noticeableFuture=rpcCallable.call();
  try {
    noticeableFuture.get();
    Assert.fail();
  }
 catch (  ExecutionException ee) {
    Assert.assertEquals(runtimeException,ee.getCause());
  }
}
