{
  try {
    _persistence.countByE2(RandomTestUtil.nextLong());
    _persistence.countByE2(0L);
  }
 catch (  Exception e) {
    Assert.fail(e.getMessage());
  }
}
