{
  Exception exception=new Exception(new RuntimeException(new NullPointerException(_message)));
  String exceptionPrefix="java.lang.Exception: java.lang.RuntimeException: " + "java.lang.NullPointerException: ";
  try {
    _log.debug(exception);
    _log.debug(null,exception);
    _log.error(exception);
    _log.error(null,exception);
    _log.fatal(exception);
    _log.fatal(null,exception);
    _log.info(exception);
    _log.info(null,exception);
    _log.trace(exception);
    _log.trace(null,exception);
    _log.warn(exception);
    _log.warn(null,exception);
    List<LoggingEvent> events=_captureAppender.getLoggingEvents();
    Assert.assertNotNull(events);
    Assert.assertEquals(12,events.size());
    for (    LoggingEvent event : events) {
      String stackTraceFirstLine=event.getThrowableInformation().getThrowableStrRep()[0];
      Assert.assertTrue(stackTraceFirstLine.startsWith(exceptionPrefix));
      char[] sanitizedMessageChars=new char[stackTraceFirstLine.length() - exceptionPrefix.length()];
      stackTraceFirstLine.getChars(exceptionPrefix.length(),stackTraceFirstLine.length(),sanitizedMessageChars,0);
      Assert.assertArrayEquals(_expectedChars,sanitizedMessageChars);
    }
  }
  finally {
    _captureAppender.close();
  }
}
