{
  DummyExceptionProcessCallable dummyExceptionProcessCallable=new DummyExceptionProcessCallable();
  Future<Serializable> future=ProcessExecutor.execute(_classPath,_createArguments(),dummyExceptionProcessCallable);
  try {
    future.get();
    fail();
  }
 catch (  ExecutionException ee) {
    assertFalse(future.isCancelled());
    assertTrue(future.isDone());
    Throwable throwable=ee.getCause();
    assertEquals(DummyExceptionProcessCallable.class.getName(),throwable.getMessage());
  }
}
