{
  try {
    doReceive(message);
  }
 catch (  Exception e) {
    _log.error(e,e);
  }
}
