{
  try {
    _log.fatal(msg,t);
  }
 catch (  Exception e) {
    printMsg(msg);
  }
}
