{
  FutureTask<Exception> futureTask=new FutureTask<Exception>(new Callable<Exception>(){
    @Override public Exception call() throws Exception {
      try {
        Thread.currentThread().checkAccess();
      }
 catch (      SecurityException se) {
        return se;
      }
      return null;
    }
  }
);
  Thread thread=new Thread(futureTask);
  thread.start();
  Exception exception=futureTask.get();
  Assert.assertNull(exception);
}
