{
  try {
    return super.get(timeout,unit);
  }
 catch (  ExecutionException ee) {
    throw new AssertionError("Not possible to throw ExecutionException",ee);
  }
}
