{
  try {
    return _method.invoke(object,_arguments);
  }
 catch (  InvocationTargetException e) {
    throw new Exception(e.getTargetException());
  }
}
